### PR TITLE
Simplify ENSIME setup

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by dwijnand** [comment]
@rorygraves Mind merging this?

**Comment by rorygraves** [comment]
LGTM

**Comment by rorygraves** [comment]
Sorry Dale too slow, can you resolve the conflicts please

**Comment by dwijnand** [comment]
Looks like @fommil's decided to strip the ENSIME config from the readme.

**Comment by dwijnand** [comment]
https://github.com/ensime/pcplod/commit/dacd7bcd8940b6865bc4f41306b941f014ee9eab#diff-04c6e90faac2675aa89e2176d2eec7d8L109

**Comment by fommil** [comment]
It's no longer necessary :-P

**Pull request closed without merging**
